/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Lexxadata Customer Scraper API
 * A structured API to search and scrape customer data from the NMS portal.
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios'
import type { AxiosRequestConfig, AxiosResponse } from 'axios'

export type BodyLoginForAccessTokenApiV1AuthLoginPostGrantType = string | null

export type BodyLoginForAccessTokenApiV1AuthLoginPostClientId = string | null

export type BodyLoginForAccessTokenApiV1AuthLoginPostClientSecret =
  | string
  | null

export interface BodyLoginForAccessTokenApiV1AuthLoginPost {
  grant_type?: BodyLoginForAccessTokenApiV1AuthLoginPostGrantType
  username: string
  password: string
  scope?: string
  client_id?: BodyLoginForAccessTokenApiV1AuthLoginPostClientId
  client_secret?: BodyLoginForAccessTokenApiV1AuthLoginPostClientSecret
}

export interface ConfigurationRequest {
  sn: string
  customer: CustomerInfo
  modem_type: string
  package: string
  eth_locks: boolean[]
}

export type ConfigurationResponseSummary = ConfigurationSummary | null

export interface ConfigurationResponse {
  message: string
  summary?: ConfigurationResponseSummary
  logs: string[]
}

export interface ConfigurationSummary {
  serial_number: string
  pppoe_user: string
  location: string
  profile: string
}

export type CustomerCreateName = string | null

export type CustomerCreateAlamat = string | null

export type CustomerCreateOltName = string | null

export type CustomerCreateOnuSn = string | null

export type CustomerCreatePppoePassword = string | null

export type CustomerCreateInterface = string | null

export type CustomerCreateOnuId = string | null

export type CustomerCreateSheet = string | null

export type CustomerCreatePaket = string | null

export interface CustomerCreate {
  name?: CustomerCreateName
  alamat?: CustomerCreateAlamat
  olt_name?: CustomerCreateOltName
  onu_sn?: CustomerCreateOnuSn
  pppoe_password?: CustomerCreatePppoePassword
  interface?: CustomerCreateInterface
  onu_id?: CustomerCreateOnuId
  sheet?: CustomerCreateSheet
  paket?: CustomerCreatePaket
  user_pppoe: string
}

export type CustomerFullDetailName = string | null

export type CustomerFullDetailAlamat = string | null

export type CustomerFullDetailOltName = string | null

export type CustomerFullDetailOnuSn = string | null

export type CustomerFullDetailPppoePassword = string | null

export type CustomerFullDetailInterface = string | null

export type CustomerFullDetailOnuId = string | null

export type CustomerFullDetailSheet = string | null

export type CustomerFullDetailPaket = string | null

export type CustomerFullDetailUpdatedAt = string | null

export type CustomerFullDetailSnmpData = SnmpData | null

export interface CustomerFullDetail {
  name?: CustomerFullDetailName
  alamat?: CustomerFullDetailAlamat
  olt_name?: CustomerFullDetailOltName
  onu_sn?: CustomerFullDetailOnuSn
  pppoe_password?: CustomerFullDetailPppoePassword
  interface?: CustomerFullDetailInterface
  onu_id?: CustomerFullDetailOnuId
  sheet?: CustomerFullDetailSheet
  paket?: CustomerFullDetailPaket
  user_pppoe: string
  updated_at?: CustomerFullDetailUpdatedAt
  tickets?: TicketWithUser[]
  snmp_data?: CustomerFullDetailSnmpData
}

export type CustomerInDBName = string | null

export type CustomerInDBAlamat = string | null

export type CustomerInDBOltName = string | null

export type CustomerInDBOnuSn = string | null

export type CustomerInDBPppoePassword = string | null

export type CustomerInDBInterface = string | null

export type CustomerInDBOnuId = string | null

export type CustomerInDBSheet = string | null

export type CustomerInDBPaket = string | null

export type CustomerInDBUpdatedAt = string | null

export interface CustomerInDB {
  name?: CustomerInDBName
  alamat?: CustomerInDBAlamat
  olt_name?: CustomerInDBOltName
  onu_sn?: CustomerInDBOnuSn
  pppoe_password?: CustomerInDBPppoePassword
  interface?: CustomerInDBInterface
  onu_id?: CustomerInDBOnuId
  sheet?: CustomerInDBSheet
  paket?: CustomerInDBPaket
  user_pppoe: string
  updated_at?: CustomerInDBUpdatedAt
}

export interface CustomerInfo {
  name: string
  address: string
  pppoe_user: string
  pppoe_pass: string
}

export type CustomerOnuDetailName = string | null

export type CustomerOnuDetailAlamat = string | null

export type CustomerOnuDetailOltName = string | null

export type CustomerOnuDetailOnuSn = string | null

export type CustomerOnuDetailPppoePassword = string | null

export type CustomerOnuDetailInterface = string | null

export type CustomerOnuDetailOnuId = string | null

export type CustomerOnuDetailSheet = string | null

export type CustomerOnuDetailPaket = string | null

export type CustomerOnuDetailUpdatedAt = string | null

export type CustomerOnuDetailType = string | null

export type CustomerOnuDetailPhaseState = string | null

export type CustomerOnuDetailSerialNumber = string | null

export type CustomerOnuDetailOnuDistance = string | null

export type CustomerOnuDetailOnlineDuration = string | null

export type CustomerOnuDetailModemLogs = string | null

export type CustomerOnuDetailRedaman = string | null

export type CustomerOnuDetailIpRemote = string | null

export interface CustomerOnuDetail {
  name?: CustomerOnuDetailName
  alamat?: CustomerOnuDetailAlamat
  olt_name?: CustomerOnuDetailOltName
  onu_sn?: CustomerOnuDetailOnuSn
  pppoe_password?: CustomerOnuDetailPppoePassword
  interface?: CustomerOnuDetailInterface
  onu_id?: CustomerOnuDetailOnuId
  sheet?: CustomerOnuDetailSheet
  paket?: CustomerOnuDetailPaket
  user_pppoe: string
  updated_at?: CustomerOnuDetailUpdatedAt
  type?: CustomerOnuDetailType
  phase_state?: CustomerOnuDetailPhaseState
  serial_number?: CustomerOnuDetailSerialNumber
  onu_distance?: CustomerOnuDetailOnuDistance
  online_duration?: CustomerOnuDetailOnlineDuration
  modem_logs?: CustomerOnuDetailModemLogs
  redaman?: CustomerOnuDetailRedaman
  ip_remote?: CustomerOnuDetailIpRemote
  eth_port?: EthPortStatus[]
}

export type CustomerUpdateName = string | null

export type CustomerUpdateAlamat = string | null

export type CustomerUpdateOltName = string | null

export type CustomerUpdateOnuSn = string | null

export type CustomerUpdatePppoePassword = string | null

export type CustomerUpdateInterface = string | null

export type CustomerUpdateOnuId = string | null

export type CustomerUpdateSheet = string | null

export type CustomerUpdatePaket = string | null

export interface CustomerUpdate {
  name?: CustomerUpdateName
  alamat?: CustomerUpdateAlamat
  olt_name?: CustomerUpdateOltName
  onu_sn?: CustomerUpdateOnuSn
  pppoe_password?: CustomerUpdatePppoePassword
  interface?: CustomerUpdateInterface
  onu_id?: CustomerUpdateOnuId
  sheet?: CustomerUpdateSheet
  paket?: CustomerUpdatePaket
}

export type CustomerwithInvoicesName = string | null

export type CustomerwithInvoicesUserPppoe = string | null

export interface CustomerwithInvoices {
  id: string
  name?: CustomerwithInvoicesName
  user_pppoe?: CustomerwithInvoicesUserPppoe
  /**
   * @minLength 1
   * @maxLength 2083
   */
  detail_url: string
  invoices?: InvoiceItem[]
}

export type DataPSBName = string | null

export type DataPSBAddress = string | null

export type DataPSBUsername = string | null

export type DataPSBPassword = string | null

export type DataPSBPaket = string | null

export interface DataPSB {
  name?: DataPSBName
  address?: DataPSBAddress
  username?: DataPSBUsername
  password?: DataPSBPassword
  paket?: DataPSBPaket
}

export interface EthPortStatus {
  is_unlocked: boolean
}

export interface ForwardTicketPayload {
  query: string
  service_impact: string
  root_cause: string
  network_impact: string
  recomended_action: string
  noc_user: string
  noc_pass: string
}

export interface HTTPValidationError {
  detail?: ValidationError[]
}

export type InvoiceItemStatus = string | null

export type InvoiceItemPackage = string | null

export type InvoiceItemPeriod = string | null

export type InvoiceItemMonth = number | null

export type InvoiceItemYear = number | null

export type InvoiceItemPaymentLink = string | null

export type InvoiceItemDescription = string | null

export interface InvoiceItem {
  status?: InvoiceItemStatus
  package?: InvoiceItemPackage
  period?: InvoiceItemPeriod
  month?: InvoiceItemMonth
  year?: InvoiceItemYear
  payment_link?: InvoiceItemPaymentLink
  description?: InvoiceItemDescription
}

export interface ListResponse {
  count: number
  running_ports: number[]
}

export interface NoOnuRequest {
  user_pppoe: number
}

export interface NoOnuResponse {
  status: string
}

export interface OnuRxRespons {
  onu_rx_data: string
}

export interface OnuStateRespons {
  onu_state_data: string
}

export type OpenTicketRequestPriority = string | null

export type OpenTicketRequestJenis = string | null

export type OpenTicketRequestHeadless = boolean | null

export type OpenTicketRequestNocUsername = string | null

export type OpenTicketRequestNocPassword = string | null

export interface OpenTicketRequest {
  query: string
  description: string
  priority?: OpenTicketRequestPriority
  jenis?: OpenTicketRequestJenis
  headless?: OpenTicketRequestHeadless
  noc_username?: OpenTicketRequestNocUsername
  noc_password?: OpenTicketRequestNocPassword
  /** Proses ticket by NOC */
  process_immediately?: boolean
}

export interface OptionsResponse {
  olt_options: string[]
  modem_options: string[]
  package_options: string[]
}

export interface PaginatedTickets {
  total_count: number
  tickets: TicketWithUser[]
}

export type ProcessTicketRequestNocUsername = string | null

export type ProcessTicketRequestNocPassword = string | null

export type ProcessTicketRequestHeadless = boolean | null

export interface ProcessTicketRequest {
  query: string
  noc_username?: ProcessTicketRequestNocUsername
  noc_password?: ProcessTicketRequestNocPassword
  headless?: ProcessTicketRequestHeadless
}

export interface RebootRequest {
  user_pppoe: number
}

export interface RebootResponse {
  status: string
}

export interface RegistSnRequest {
  user_pppoe: number
  sn: string
}

export interface RegistSnResponse {
  status: string
}

export type SnmpDataOltName = string | null

export type SnmpDataInterface = string | null

export type SnmpDataName = string | null

export type SnmpDataAddress = string | null

export type SnmpDataModemType = string | null

export type SnmpDataStatus = string | null

export type SnmpDataRxPowerDbm = number | null

export type SnmpDataRxPowerStr = string | null

export type SnmpDataLastUpdated = string | null

export interface SnmpData {
  sn: string
  olt_name?: SnmpDataOltName
  interface?: SnmpDataInterface
  name?: SnmpDataName
  address?: SnmpDataAddress
  modem_type?: SnmpDataModemType
  status?: SnmpDataStatus
  rx_power_dbm?: SnmpDataRxPowerDbm
  rx_power_str?: SnmpDataRxPowerStr
  last_updated?: SnmpDataLastUpdated
}

export type SortDirection = (typeof SortDirection)[keyof typeof SortDirection]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SortDirection = {
  asc: 'asc',
  desc: 'desc',
} as const

export interface StopResponse {
  port: number
  pid: number
  message: string
}

export interface TerminalResponse {
  port: number
  pid: number
  command: string
  message: string
}

export type TicketClosePayloadHeadlessMode = boolean | null

export type TicketClosePayloadActionCloseNotes = string | null

export interface TicketClosePayload {
  close_reason: string
  headless_mode?: TicketClosePayloadHeadlessMode
  noc_user: string
  noc_pass: string
  query: string
  action_close_notes?: TicketClosePayloadActionCloseNotes
}

export type TicketSortColumn =
  (typeof TicketSortColumn)[keyof typeof TicketSortColumn]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TicketSortColumn = {
  last_updated: 'last_updated',
  status: 'status',
  nama: 'nama',
  tiket: 'tiket',
  pic: 'pic',
} as const

export type TicketWithUserTanggal = string | null

export type TicketWithUserWaktu = string | null

export type TicketWithUserNama = string | null

export type TicketWithUserKendala = string | null

export type TicketWithUserStatus = string | null

export type TicketWithUserPic = string | null

export type TicketWithUserLastUpdated = string | null

export type TicketWithUserPicUser = UserBase | null

export interface TicketWithUser {
  id: number
  tiket: string
  tanggal?: TicketWithUserTanggal
  waktu?: TicketWithUserWaktu
  nama?: TicketWithUserNama
  kendala?: TicketWithUserKendala
  status?: TicketWithUserStatus
  pic?: TicketWithUserPic
  last_updated?: TicketWithUserLastUpdated
  pic_user?: TicketWithUserPicUser
}

export interface Token {
  access_token: string
  token_type: string
}

export interface UnconfiguredOnt {
  sn: string
  pon_port: string
  pon_slot: string
}

export type UserFullName = string | null

export type UserRole = string | null

export interface User {
  username: string
  full_name?: UserFullName
  role?: UserRole
  id: number
}

export type UserBaseFullName = string | null

export type UserBaseRole = string | null

export interface UserBase {
  username: string
  full_name?: UserBaseFullName
  role?: UserBaseRole
}

export type UserCreateFullName = string | null

export type UserCreateRole = string | null

export interface UserCreate {
  username: string
  full_name?: UserCreateFullName
  role?: UserCreateRole
  password: string
}

export interface UserStats {
  open_tickets: number
  proses_tickets: number
  total_active: number
}

export type ValidationErrorLocItem = string | number

export interface ValidationError {
  loc: ValidationErrorLocItem[]
  msg: string
  type: string
}

export type GetUserStatsEndpointApiV1UsersUsernameStatsGetParams = {
  interval?: GetUserStatsEndpointApiV1UsersUsernameStatsGetInterval
}

export type GetUserStatsEndpointApiV1UsersUsernameStatsGetInterval =
  (typeof GetUserStatsEndpointApiV1UsersUsernameStatsGetInterval)[keyof typeof GetUserStatsEndpointApiV1UsersUsernameStatsGetInterval]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserStatsEndpointApiV1UsersUsernameStatsGetInterval = {
  week: 'week',
  month: 'month',
  year: 'year',
} as const

export type SearchOrGetAllCustomersApiV1DataFiberGetParams = {
  /**
   * Search query
   */
  q?: string | null
}

export type GetFastCustomerDetailsApiV1CustomerInvoicesGetParams = {
  /**
   * @minLength 1
   */
  query: string
}

export type SearchTicketApiV1TicketSearchGetParams = {
  query: string
}

export type SearchTicketApiV1TicketSearchGet200 = { [key: string]: unknown }

export type OpenAndProcessTicketApiV1TicketPost200 = { [key: string]: unknown }

export type ProcessTicketApiV1TicketProsesTicketPost200 = {
  [key: string]: unknown
}

export type GetCustomerAndOltDetailsApiV1OnuDetailSearchGetParams = {
  /**
   * Cari berdasarkan PPPoE, SN, atau Nama
   */
  q: string
}

export type GetCustomerAndStateApiV1OnuOnuStateGetParams = {
  /**
   * Cari berdasarkan PPPoe, SN, atau nama
   */
  q: string
}

export type GetCustomerAndOnuRxApiV1OnuOnuRxGetParams = {
  /**
   * Cari berdasarkan PPPoE, SN, atau Nama
   */
  q: string
}

export type ReadPaginatedTicketsApiV1KomplainTicketsGetParams = {
  /**
   * @minimum 1
   */
  page?: number
  /**
   * @minimum 1
   * @maximum 100
   */
  size?: number
  sort_by?: TicketSortColumn
  sort_dir?: SortDirection
  day?: string | null
}

export const getLexxadataCustomerScraperAPI = () => {
  /**
   * @summary Root
   */
  const rootGet = <TData = AxiosResponse<unknown>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/`, options)
  }

  /**
   * @summary Login For Access Token
   */
  const loginForAccessTokenApiV1AuthLoginPost = <TData = AxiosResponse<Token>>(
    bodyLoginForAccessTokenApiV1AuthLoginPost: BodyLoginForAccessTokenApiV1AuthLoginPost,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    const formUrlEncoded = new URLSearchParams()
    if (
      bodyLoginForAccessTokenApiV1AuthLoginPost.grant_type !== undefined &&
      bodyLoginForAccessTokenApiV1AuthLoginPost.grant_type !== null
    ) {
      formUrlEncoded.append(
        `grant_type`,
        bodyLoginForAccessTokenApiV1AuthLoginPost.grant_type,
      )
    }
    formUrlEncoded.append(
      `username`,
      bodyLoginForAccessTokenApiV1AuthLoginPost.username,
    )
    formUrlEncoded.append(
      `password`,
      bodyLoginForAccessTokenApiV1AuthLoginPost.password,
    )
    if (bodyLoginForAccessTokenApiV1AuthLoginPost.scope !== undefined) {
      formUrlEncoded.append(
        `scope`,
        bodyLoginForAccessTokenApiV1AuthLoginPost.scope,
      )
    }
    if (
      bodyLoginForAccessTokenApiV1AuthLoginPost.client_id !== undefined &&
      bodyLoginForAccessTokenApiV1AuthLoginPost.client_id !== null
    ) {
      formUrlEncoded.append(
        `client_id`,
        bodyLoginForAccessTokenApiV1AuthLoginPost.client_id,
      )
    }
    if (
      bodyLoginForAccessTokenApiV1AuthLoginPost.client_secret !== undefined &&
      bodyLoginForAccessTokenApiV1AuthLoginPost.client_secret !== null
    ) {
      formUrlEncoded.append(
        `client_secret`,
        bodyLoginForAccessTokenApiV1AuthLoginPost.client_secret,
      )
    }

    return axios.default.post(`/api/v1/auth/login`, formUrlEncoded, options)
  }

  /**
   * @summary Get All Users
   */
  const getAllUsersApiV1UsersGet = <TData = AxiosResponse<User[]>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/users/`, options)
  }

  /**
   * @summary Add User
   */
  const addUserApiV1UsersPost = <TData = AxiosResponse<User>>(
    userCreate: UserCreate,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(`/api/v1/users/`, userCreate, options)
  }

  /**
   * @summary Get Current User Me
   */
  const getCurrentUserMeApiV1UsersMeGet = <TData = AxiosResponse<User>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/users/me`, options)
  }

  /**
   * @summary Get User Stats Endpoint
   */
  const getUserStatsEndpointApiV1UsersUsernameStatsGet = <
    TData = AxiosResponse<UserStats>,
  >(
    username: string,
    params?: GetUserStatsEndpointApiV1UsersUsernameStatsGetParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/users/${username}/stats`, {
      ...options,
      params: { ...params, ...options?.params },
    })
  }

  /**
   * @summary Create New Customer
   */
  const createNewCustomerApiV1DataFiberPost = <
    TData = AxiosResponse<CustomerInDB>,
  >(
    customerCreate: CustomerCreate,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(`/api/v1/data_fiber/`, customerCreate, options)
  }

  /**
   * @summary Search Or Get All Customers
   */
  const searchOrGetAllCustomersApiV1DataFiberGet = <
    TData = AxiosResponse<CustomerInDB[]>,
  >(
    params?: SearchOrGetAllCustomersApiV1DataFiberGetParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/data_fiber/`, {
      ...options,
      params: { ...params, ...options?.params },
    })
  }

  /**
   * @summary Read Customer Full Detail
   */
  const readCustomerFullDetailApiV1DataFiberPppoeUserFullDetailGet = <
    TData = AxiosResponse<CustomerFullDetail>,
  >(
    pppoeUser: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(
      `/api/v1/data_fiber/${pppoeUser}/full_detail`,
      options,
    )
  }

  /**
   * @summary Read Customer
   */
  const readCustomerApiV1DataFiberPppoeUserGet = <
    TData = AxiosResponse<CustomerInDB>,
  >(
    pppoeUser: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/data_fiber/${pppoeUser}`, options)
  }

  /**
   * @summary Update Existing Customer
   */
  const updateExistingCustomerApiV1DataFiberPppoeUserPut = <
    TData = AxiosResponse<CustomerInDB>,
  >(
    pppoeUser: string,
    customerUpdate: CustomerUpdate,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.put(
      `/api/v1/data_fiber/${pppoeUser}`,
      customerUpdate,
      options,
    )
  }

  /**
   * @summary Delete Existing Customer
   */
  const deleteExistingCustomerApiV1DataFiberPppoeUserDelete = <
    TData = AxiosResponse<CustomerInDB>,
  >(
    pppoeUser: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.delete(`/api/v1/data_fiber/${pppoeUser}`, options)
  }

  /**
 * Starts a new ttyd session on a random free port.
The terminal will run the 'bash' command.
 * @summary Start Terminal
 */
  const startTerminalApiV1CliStartTerminalPost = <
    TData = AxiosResponse<TerminalResponse>,
  >(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(`/api/v1/cli/start_terminal`, undefined, options)
  }

  /**
   * Stops a running ttyd session by its port number.
   * @summary Stop Terminal
   */
  const stopTerminalApiV1CliStopTerminalPortPost = <
    TData = AxiosResponse<StopResponse>,
  >(
    port: number,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/cli/stop_terminal/${port}`,
      undefined,
      options,
    )
  }

  /**
   * Lists all ttyd sessions started by this API.
   * @summary List Running Terminals
   */
  const listRunningTerminalsApiV1CliRunningTerminalsGet = <
    TData = AxiosResponse<ListResponse>,
  >(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/cli/running_terminals`, options)
  }

  /**
   * @summary Get Psb Data
   */
  const getPsbDataApiV1CustomerPsbGet = <TData = AxiosResponse<DataPSB[]>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/customer/psb`, options)
  }

  /**
   * @summary Get Fast Customer Details
   */
  const getFastCustomerDetailsApiV1CustomerInvoicesGet = <
    TData = AxiosResponse<CustomerwithInvoices[]>,
  >(
    params: GetFastCustomerDetailsApiV1CustomerInvoicesGetParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/customer/invoices`, {
      ...options,
      params: { ...params, ...options?.params },
    })
  }

  /**
   * @summary Search Ticket
   */
  const searchTicketApiV1TicketSearchGet = <
    TData = AxiosResponse<SearchTicketApiV1TicketSearchGet200>,
  >(
    params: SearchTicketApiV1TicketSearchGetParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/ticket/search`, {
      ...options,
      params: { ...params, ...options?.params },
    })
  }

  /**
   * @summary Open And Process Ticket
   */
  const openAndProcessTicketApiV1TicketPost = <
    TData = AxiosResponse<OpenAndProcessTicketApiV1TicketPost200>,
  >(
    openTicketRequest: OpenTicketRequest,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(`/api/v1/ticket/`, openTicketRequest, options)
  }

  /**
   * @summary Process Ticket
   */
  const processTicketApiV1TicketProsesTicketPost = <
    TData = AxiosResponse<ProcessTicketApiV1TicketProsesTicketPost200>,
  >(
    processTicketRequest: ProcessTicketRequest,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/ticket/proses-ticket/`,
      processTicketRequest,
      options,
    )
  }

  /**
   * @summary Close Ticket
   */
  const closeTicketApiV1TicketCloseTicketPost = <
    TData = AxiosResponse<unknown>,
  >(
    ticketClosePayload: TicketClosePayload,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/ticket/close-ticket/`,
      ticketClosePayload,
      options,
    )
  }

  /**
   * @summary Forward Ticket Endpoint
   */
  const forwardTicketEndpointApiV1TicketForwardTicketPost = <
    TData = AxiosResponse<unknown>,
  >(
    forwardTicketPayload: ForwardTicketPayload,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/ticket/forward-ticket/`,
      forwardTicketPayload,
      options,
    )
  }

  /**
   * Mengembalikan semua opsi yang dibutuhkan untuk form di frontend.
   * @summary Get Options
   */
  const getOptionsApiV1ConfigApiOptionsGet = <
    TData = AxiosResponse<OptionsResponse>,
  >(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/config/api/options`, options)
  }

  /**
   * Mendeteksi semua unconfigured ONT pada OLT yang dipilih.
   * @summary Detect Uncfg Onts
   */
  const detectUncfgOntsApiV1ConfigApiOltsOltNameDetectOntsGet = <
    TData = AxiosResponse<UnconfiguredOnt[]>,
  >(
    oltName: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(
      `/api/v1/config/api/olts/${oltName}/detect-onts`,
      options,
    )
  }

  /**
   * Menjalankan proses konfigurasi untuk satu ONT.
   * @summary Run Configuration
   */
  const runConfigurationApiV1ConfigApiOltsOltNameConfigurePost = <
    TData = AxiosResponse<ConfigurationResponse>,
  >(
    oltName: string,
    configurationRequest: ConfigurationRequest,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(
      `/api/v1/config/api/olts/${oltName}/configure`,
      configurationRequest,
      options,
    )
  }

  /**
   * @summary Get Customer And Olt Details
   */
  const getCustomerAndOltDetailsApiV1OnuDetailSearchGet = <
    TData = AxiosResponse<CustomerOnuDetail>,
  >(
    params: GetCustomerAndOltDetailsApiV1OnuDetailSearchGetParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/onu/detail-search`, {
      ...options,
      params: { ...params, ...options?.params },
    })
  }

  /**
   * @summary Get Customer And State
   */
  const getCustomerAndStateApiV1OnuOnuStateGet = <
    TData = AxiosResponse<OnuStateRespons>,
  >(
    params: GetCustomerAndStateApiV1OnuOnuStateGetParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/onu/onu-state`, {
      ...options,
      params: { ...params, ...options?.params },
    })
  }

  /**
   * @summary Get Customer And Onu Rx
   */
  const getCustomerAndOnuRxApiV1OnuOnuRxGet = <
    TData = AxiosResponse<OnuRxRespons>,
  >(
    params: GetCustomerAndOnuRxApiV1OnuOnuRxGetParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/onu/onu-rx`, {
      ...options,
      params: { ...params, ...options?.params },
    })
  }

  /**
   * @summary Reboot Onu By Pppoe
   */
  const rebootOnuByPppoeApiV1OnuRebootOnuPost = <
    TData = AxiosResponse<RebootResponse>,
  >(
    rebootRequest: RebootRequest,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(`/api/v1/onu/reboot-onu`, rebootRequest, options)
  }

  /**
   * @summary No Onu By Pppoe
   */
  const noOnuByPppoeApiV1OnuNoOnuPost = <TData = AxiosResponse<NoOnuResponse>>(
    noOnuRequest: NoOnuRequest,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(`/api/v1/onu/no-onu`, noOnuRequest, options)
  }

  /**
   * @summary Regist Sn By Pppoe
   */
  const registSnByPppoeApiV1OnuRegistSnPost = <
    TData = AxiosResponse<RegistSnResponse>,
  >(
    registSnRequest: RegistSnRequest,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(`/api/v1/onu/regist-sn`, registSnRequest, options)
  }

  /**
   * @summary Read Paginated Tickets
   */
  const readPaginatedTicketsApiV1KomplainTicketsGet = <
    TData = AxiosResponse<PaginatedTickets>,
  >(
    params?: ReadPaginatedTicketsApiV1KomplainTicketsGetParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/komplain/tickets`, {
      ...options,
      params: { ...params, ...options?.params },
    })
  }

  /**
   * @summary Notify Clients
   */
  const notifyClientsApiV1KomplainNotifyPost = <TData = AxiosResponse<unknown>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.post(`/api/v1/komplain/notify`, undefined, options)
  }

  /**
   * @summary Get All Snmp Data
   */
  const getAllSnmpDataApiV1SnmpGet = <TData = AxiosResponse<SnmpData[]>>(
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/snmp/`, options)
  }

  /**
   * @summary Get Snmp Data By Sn
   */
  const getSnmpDataBySnApiV1SnmpSnGet = <TData = AxiosResponse<SnmpData>>(
    sn: string,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.default.get(`/api/v1/snmp/${sn}`, options)
  }

  return {
    rootGet,
    loginForAccessTokenApiV1AuthLoginPost,
    getAllUsersApiV1UsersGet,
    addUserApiV1UsersPost,
    getCurrentUserMeApiV1UsersMeGet,
    getUserStatsEndpointApiV1UsersUsernameStatsGet,
    createNewCustomerApiV1DataFiberPost,
    searchOrGetAllCustomersApiV1DataFiberGet,
    readCustomerFullDetailApiV1DataFiberPppoeUserFullDetailGet,
    readCustomerApiV1DataFiberPppoeUserGet,
    updateExistingCustomerApiV1DataFiberPppoeUserPut,
    deleteExistingCustomerApiV1DataFiberPppoeUserDelete,
    startTerminalApiV1CliStartTerminalPost,
    stopTerminalApiV1CliStopTerminalPortPost,
    listRunningTerminalsApiV1CliRunningTerminalsGet,
    getPsbDataApiV1CustomerPsbGet,
    getFastCustomerDetailsApiV1CustomerInvoicesGet,
    searchTicketApiV1TicketSearchGet,
    openAndProcessTicketApiV1TicketPost,
    processTicketApiV1TicketProsesTicketPost,
    closeTicketApiV1TicketCloseTicketPost,
    forwardTicketEndpointApiV1TicketForwardTicketPost,
    getOptionsApiV1ConfigApiOptionsGet,
    detectUncfgOntsApiV1ConfigApiOltsOltNameDetectOntsGet,
    runConfigurationApiV1ConfigApiOltsOltNameConfigurePost,
    getCustomerAndOltDetailsApiV1OnuDetailSearchGet,
    getCustomerAndStateApiV1OnuOnuStateGet,
    getCustomerAndOnuRxApiV1OnuOnuRxGet,
    rebootOnuByPppoeApiV1OnuRebootOnuPost,
    noOnuByPppoeApiV1OnuNoOnuPost,
    registSnByPppoeApiV1OnuRegistSnPost,
    readPaginatedTicketsApiV1KomplainTicketsGet,
    notifyClientsApiV1KomplainNotifyPost,
    getAllSnmpDataApiV1SnmpGet,
    getSnmpDataBySnApiV1SnmpSnGet,
  }
}
export type RootGetResult = AxiosResponse<unknown>
export type LoginForAccessTokenApiV1AuthLoginPostResult = AxiosResponse<Token>
export type GetAllUsersApiV1UsersGetResult = AxiosResponse<User[]>
export type AddUserApiV1UsersPostResult = AxiosResponse<User>
export type GetCurrentUserMeApiV1UsersMeGetResult = AxiosResponse<User>
export type GetUserStatsEndpointApiV1UsersUsernameStatsGetResult =
  AxiosResponse<UserStats>
export type CreateNewCustomerApiV1DataFiberPostResult =
  AxiosResponse<CustomerInDB>
export type SearchOrGetAllCustomersApiV1DataFiberGetResult = AxiosResponse<
  CustomerInDB[]
>
export type ReadCustomerFullDetailApiV1DataFiberPppoeUserFullDetailGetResult =
  AxiosResponse<CustomerFullDetail>
export type ReadCustomerApiV1DataFiberPppoeUserGetResult =
  AxiosResponse<CustomerInDB>
export type UpdateExistingCustomerApiV1DataFiberPppoeUserPutResult =
  AxiosResponse<CustomerInDB>
export type DeleteExistingCustomerApiV1DataFiberPppoeUserDeleteResult =
  AxiosResponse<CustomerInDB>
export type StartTerminalApiV1CliStartTerminalPostResult =
  AxiosResponse<TerminalResponse>
export type StopTerminalApiV1CliStopTerminalPortPostResult =
  AxiosResponse<StopResponse>
export type ListRunningTerminalsApiV1CliRunningTerminalsGetResult =
  AxiosResponse<ListResponse>
export type GetPsbDataApiV1CustomerPsbGetResult = AxiosResponse<DataPSB[]>
export type GetFastCustomerDetailsApiV1CustomerInvoicesGetResult =
  AxiosResponse<CustomerwithInvoices[]>
export type SearchTicketApiV1TicketSearchGetResult =
  AxiosResponse<SearchTicketApiV1TicketSearchGet200>
export type OpenAndProcessTicketApiV1TicketPostResult =
  AxiosResponse<OpenAndProcessTicketApiV1TicketPost200>
export type ProcessTicketApiV1TicketProsesTicketPostResult =
  AxiosResponse<ProcessTicketApiV1TicketProsesTicketPost200>
export type CloseTicketApiV1TicketCloseTicketPostResult = AxiosResponse<unknown>
export type ForwardTicketEndpointApiV1TicketForwardTicketPostResult =
  AxiosResponse<unknown>
export type GetOptionsApiV1ConfigApiOptionsGetResult =
  AxiosResponse<OptionsResponse>
export type DetectUncfgOntsApiV1ConfigApiOltsOltNameDetectOntsGetResult =
  AxiosResponse<UnconfiguredOnt[]>
export type RunConfigurationApiV1ConfigApiOltsOltNameConfigurePostResult =
  AxiosResponse<ConfigurationResponse>
export type GetCustomerAndOltDetailsApiV1OnuDetailSearchGetResult =
  AxiosResponse<CustomerOnuDetail>
export type GetCustomerAndStateApiV1OnuOnuStateGetResult =
  AxiosResponse<OnuStateRespons>
export type GetCustomerAndOnuRxApiV1OnuOnuRxGetResult =
  AxiosResponse<OnuRxRespons>
export type RebootOnuByPppoeApiV1OnuRebootOnuPostResult =
  AxiosResponse<RebootResponse>
export type NoOnuByPppoeApiV1OnuNoOnuPostResult = AxiosResponse<NoOnuResponse>
export type RegistSnByPppoeApiV1OnuRegistSnPostResult =
  AxiosResponse<RegistSnResponse>
export type ReadPaginatedTicketsApiV1KomplainTicketsGetResult =
  AxiosResponse<PaginatedTickets>
export type NotifyClientsApiV1KomplainNotifyPostResult = AxiosResponse<unknown>
export type GetAllSnmpDataApiV1SnmpGetResult = AxiosResponse<SnmpData[]>
export type GetSnmpDataBySnApiV1SnmpSnGetResult = AxiosResponse<SnmpData>
